import type { NextPage } from 'next';
import Head from 'next/head';
import Artical from '../components/artical/Artical';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>News Articals App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Artical />
    </div>
  );
};

export default Home;
